spring.application.name=notification-api

# Para rodar local: use localhost:5433
spring.datasource.url=jdbc:postgresql://localhost:5433/notification_api
spring.datasource.username=postgres
spring.datasource.password=12243648

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.locations=classpath:db/migration

# Email SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gustavo16378@gmail.com
spring.mail.password=nyjexnmscrrdqsph
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=gustavo16378@gmail.com

# RabbitMQ local
spring.rabbitmq.host=rabbitmq   # <-- para Docker Compose!
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest